HHBLITS_PATH: /data3/software/boctopus2/src/app/hhsuite-2.0.16-linux-x86_64
HHBLITS_DB_PATH: /data/hhsuite/uniprot20_2013_03/uniprot20_2013_03
blastpath: /data3/software/boctopus2/src/app/blast-2.2.26/bin
rpath: /usr/bin
